---
title: "Recruitment"
author: "Yasmine Gillespie"
date: "5/16/2020"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE}
library(knitr, warn.conflicts = F, quietly = T)
library(tidyr, warn.conflicts = F, quietly = T)
library(dplyr, warn.conflicts = F, quietly = T)
library(ggplot2, warn.conflicts = F, quietly = T)
library(keyringr, warn.conflicts = F, quietly = T)
library(redcapAPI, warn.conflicts = F, quietly = T)
library(REDCapR, warn.conflicts = F, quietly = T)
library(lubridate, warn.conflicts = F, quietly = T)
#this is a pakage that will help create tables
library(formattable, warn.conflicts = F,quietly = T)
#Create path to and api link to RedCaps
credential_label <- "beach_api"
credential_path <- paste(Sys.getenv("USERPROFILE"), '\\DPAPI\\passwords\\', Sys.info()["nodename"], '\\', credential_label, '.txt', sep="")
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
beach_token<-decrypt_dpapi_pw(credential_path)
```

```{r variable selection, include=FALSE}
# Create connections
rcon <- redcapConnection(url=uri, token=beach_token)
# variables
desired_fields=c("test_id","redcap_event_name",
                 "beach_part_drop_out",
                 "beachphone_age",
                 "beachphone_prepreg_bmi",
                 "beachphone_hear_about_us",
                 "beach_consent_date1",
                 "beach_study_complete")
# participants
participant.records.v1=c("BLS001A",
                         "BLS002A",
                         "BLS003A",
                         "BLS007A",
                         "BLS008A",
                         "BLS011A",
                         "BLS012A",
                         "BLS013A",
                         "BLS014A",
                         "BLS016A",
                         "BLS019A",
                         "BLS020A",
                         "BLS023A",
                         "BLS025A",
                         "BLS027A",
                         "BLS028A",
                         "BLS030A",
                         "BLS032A",
                         "BLS033A",
                         "BLS034A",
                         "BLS035A",
                         "BLS036A",
                         "BLS038A",
                         "BLS040A")
# pull data
ds <- data.frame(desired_fields)
dat<- redcap_read(
  batch_size=300,
  records= participant.records.v1,
  redcap_uri = uri, 
  token      = beach_token, 
  fields     = desired_fields
)$data
head(dat)
```
```{r variable selection, include=FALSE}
# recode encounter type
dat.f=dat %>%
    #use mutate(new column = recode(current column to be recoded, "variable in column"="new variable name"))
    mutate(beachphone_hear_about_us_new = recode(beachphone_hear_about_us, "1"="Flyer","3"="Facebook","5"="Other"))%>%
    replace_na(list( beachphone_hear_about_us_new = "Didn't Respond"))%>%
    mutate(beachphone_pass_fail_new = recode(beachphone_pass_fail, "1"="pass","0"="fail"))%>%
    mutate(beach_consent_date1_new = recode(beach_consent_date1, "1"="Consented","0"="not Consented"))
```

```{r variable selection, include=FALSE}
Age <- ds_some_rows_v1%>%
    filter(!is.na(analysis_mat_age))

BMI <- ds_some_rows_v1%>%
    filter(!is.na(analysis_bmi))
```
